version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network

  app1:
    build: app1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - network

  app2:
    build: app2
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - network

volumes:
  db:

networks:
  network:
